name: Hello on PR or Issue

on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]

jobs:
  welcome:
    if: github.event.action == 'opened'
    uses: rladies/jinx/.github/workflows/reusable-welcome-contributor.yml@main
    secrets:
      JINX_APP_ID: ${{ secrets.JINX_APP_ID }}
      JINX_PRIVATE_KEY: ${{ secrets.JINX_PRIVATE_KEY }}

  thank:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: rladies/jinx/.github/workflows/reusable-thank-contributor.yml@main
    secrets:
      JINX_APP_ID: ${{ secrets.JINX_APP_ID }}
      JINX_PRIVATE_KEY: ${{ secrets.JINX_PRIVATE_KEY }}
