name: Knit readme and aggregate website JSONs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'data/content/**'
      - 'data/packages/**'
      - 'README.Rmd'
      - 'scripts/generate_website_jsons.R'
      - '.github/workflows/knit_readme.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  knit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Render readme files
        run: rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}

      - name: Aggregate website JSONs
        run: source("scripts/generate_website_jsons.R")
        shell: Rscript {0}

      - name: Commit data
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md data/website
          git diff --cached --quiet || git commit -m 'Update README and aggregated website JSONs'
          git push origin || echo "Nothing to push"
